apiVersion: v1
kind: ServiceAccount
metadata:
  name: csi-attacher-sa
  namespace: default

---
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: csi-attacher-role
  namespace: default
subjects:
  - kind: ServiceAccount
    name: csi-attacher-sa
    namespace: default
roleRef: 
  kind: ClusterRole
  name: system:csi-external-attacher
  apiGroup: rbac.authorization.k8s.io

---
kind: StatefulSet
apiVersion: apps/v1beta1
metadata:
  name: synology-csi-attacher
spec:
  serviceName: "synology-csi-attacher"
  replicas: 1
  template:
    metadata:
      labels:
        app: synology-csi-attacher
    spec:
      serviceAccount: csi-attacher-sa
      containers:
        - name: csi-attacher
          securityContext:
            privileged: true
            capabilities:
              add: ["SYS_ADMIN"]
            allowPrivilegeEscalation: true
          image: quay.io/k8scsi/csi-attacher:v0.4.1
          args:
            - --v=5
            - --csi-address=$(ADDRESS)
          env:
            - name: ADDRESS
              value: /var/lib/csi/sockets/pluginproxy/csi.sock
          imagePullPolicy: Always
          volumeMounts:
            - name: socket-dir
              mountPath: /var/lib/csi/sockets/pluginproxy/
        - name: csi-plugin
          securityContext:
            privileged: true
            capabilities:
              add: ["SYS_ADMIN"]
            allowPrivilegeEscalation: true
          image: jparklab/synology-csi:v0.4.1
          args :
            - --nodeid
            - NotUsed
            - --endpoint=$(CSI_ENDPOINT)
            - --synology-config
            - /etc/synology/syno-config.yml
            - --logtostderr
            - --v=5
          env:
            - name: CSI_ENDPOINT
              value: unix:///var/lib/csi/sockets/pluginproxy/csi.sock
          imagePullPolicy: Always
          volumeMounts:
            - name: socket-dir
              mountPath: /var/lib/csi/sockets/pluginproxy/
            - name: synology-config
              mountPath: /etc/synology
              readOnly: true
      volumes:
        - name: socket-dir
          emptyDir: {}
        - name: synology-config
          secret:
            secretName: synology-config
