apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  annotations:
    # set this to false if you do not want this storage class to be default
    storageclass.kubernetes.io/is-default-class: "true"
  name: synology-iscsi-storage
provisioner: csi.synology.com
reclaimPolicy: Delete
