apiVersion: v1
kind: ServiceAccount
metadata:
  name: csi-provisioner-sa
  namespace: default

---

kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: csi-provisioner-role
  namespace: default
subjects:
  - kind: ServiceAccount
    name: csi-provisioner-sa
    namespace: default
roleRef:
  kind: ClusterRole
  name: system:csi-external-provisioner
  apiGroup: rbac.authorization.k8s.io

---
kind: StatefulSet
apiVersion: apps/v1beta1
metadata:
  name: synology-csi-provisioner
spec:
  serviceName: "synology-csi-provisioner"
  replicas: 1
  template:
    metadata:
      labels:
        app: synology-csi-provisioner
    spec:
      serviceAccount: csi-provisioner-sa
      containers:
        - name: csi-provisioner
          securityContext:
            privileged: true
            capabilities:
              add: ["SYS_ADMIN"]
            allowPrivilegeEscalation: true
          image: quay.io/k8scsi/csi-provisioner:v1.0.0
          args:
            - --provisioner=csi.synology.com
            - --csi-address=$(ADDRESS)
            - --v=5
          env:
            - name: ADDRESS
              value: /var/lib/csi/sockets/pluginproxy/csi.sock
          imagePullPolicy: Always
          volumeMounts:
            - name: socket-dir
              mountPath: /var/lib/csi/sockets/pluginproxy/

        - name: csi-plugin
          securityContext:
            privileged: true
            capabilities:
              add: ["SYS_ADMIN"]
            allowPrivilegeEscalation: true
          image: jparklab/synology-csi:v1.0.0
          args :
            - --nodeid
            - NotUsed
            - --endpoint=$(CSI_ENDPOINT)
            - --synology-config
            - /etc/synology/syno-config.yml
            - --logtostderr
            - --v=8
          env:
            - name: CSI_ENDPOINT
              value: unix:///var/lib/csi/sockets/pluginproxy/csi.sock
          imagePullPolicy: Always
          volumeMounts:
            - name: socket-dir
              mountPath: /var/lib/csi/sockets/pluginproxy/
            - name: synology-config
              mountPath: /etc/synology
              readOnly: true
      volumes:
        - name: socket-dir
          emptyDir: {}
        - name: synology-config
          secret:
            secretName: synology-config
