name: Validate pull request

on:
  pull_request:
    branches: master

jobs:
  buildx:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        id: buildx
        uses: crazy-max/ghaction-docker-buildx@v1
        with:
          version: latest

      - name: Run Buildx
        env:
          # Removed linux/arm/v7 as build gets stuck while building arm/v7
          # Should be re-added once the build issue is resolved
          # PLATFORMS: "linux/386,linux/amd64,linux/arm/v7,linux/arm64,linux/ppc64le"
          PLATFORMS: "linux/386,linux/amd64,linux/arm64,linux/ppc64le"
        run: ./build.sh -t jparklab/synology-csi
